// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://uihnpebacpcndtkdizxd.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaG5wZWJhY3BjbmR0a2RpenhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTk4ODIsImV4cCI6MjA2NDkzNTg4Mn0.is_-3d_8FWrU7ge8y69zV6U4-QZhilk_FOH26clxqBo';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);